/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view;

/**
 *
 * @author gabriela
 */
public class BuscaProjetoView extends javax.swing.JPanel {

    /**
     * Creates new form BuscaProjetoView
     */
    public BuscaProjetoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        projetoLabel = new javax.swing.JLabel();
        projetoComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Buscar Projeto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        projetoLabel.setText("Selecione o projeto:");
        add(projetoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        projetoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção" }));
        add(projetoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 390, -1));

        cancelButton.setText("Cancelar");
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        buscarButton.setText("Buscar Informações");
        add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 150, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> projetoComboBox;
    private javax.swing.JLabel projetoLabel;
    // End of variables declaration//GEN-END:variables
}
