/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mpsbr.control.AvaliacaoControl;
import mpsbr.control.NivelControl;
import mpsbr.control.ProjetoControl;

/**
 *
 * @author gabriela
 */
public class MainView extends javax.swing.JFrame implements Runnable{

    
    public static final String CADASTRA_PRJ = "cadPrj";
    public static final String BUSCA_PRJ = "srcPrj";
    public static final String SIMULA_AVL = "simAvl";
    public static final String CONSULTA_AVL = "consAvl";
    public static final String CADASTRA_XML = "regXML";
    public static final String CADASTRA_USR = "regUsr";
    
    
    /**
     * Creates new form mainView
     */
    
    private final static JFileChooser FILECHOOSER = new JFileChooser();
    
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadProjMenuItem = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        buscProj = new javax.swing.JMenuItem();
        remProjMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        cadastrarXMLMenulItem = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Usuários");

        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Alterar Senha");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Remover");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Projetos");

        cadProjMenuItem.setText("Cadastrar");
        cadProjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProjMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(cadProjMenuItem);

        jMenuItem5.setText("Alterar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        buscProj.setText("Consultar");
        buscProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscProjActionPerformed(evt);
            }
        });
        jMenu2.add(buscProj);

        remProjMenuItem.setText("Remover");
        remProjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remProjMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(remProjMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Avaliações");

        jMenuItem8.setText("Simular Avaliação");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Consultar Avaliações Anteriores");
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Níveis MPS.BR");

        jMenu5.setText("Cadastrar");

        cadastrarXMLMenulItem.setText("via XML");
        cadastrarXMLMenulItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarXMLMenulItemActionPerformed(evt);
            }
        });
        jMenu5.add(cadastrarXMLMenulItem);

        jMenuItem10.setText("via Formulário");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenu4.add(jMenu5);

        jMenuItem11.setText("Alterar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Consultar");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Remover");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void cadastrarXMLMenulItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarXMLMenulItemActionPerformed
        CardLayout cl = (CardLayout)this.mainPanel.getLayout();
        cl.show(this.mainPanel, MainView.CADASTRA_XML);
    }//GEN-LAST:event_cadastrarXMLMenulItemActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void remProjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remProjMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)this.mainPanel.getLayout();
        cl.show(this.mainPanel, "REM PROJ");
    }//GEN-LAST:event_remProjMenuItemActionPerformed

    private void cadProjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProjMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)this.mainPanel.getLayout();
        cl.show(this.mainPanel, MainView.CADASTRA_PRJ);
    }//GEN-LAST:event_cadProjMenuItemActionPerformed

    private void buscProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscProjActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)this.mainPanel.getLayout();
        cl.show(this.mainPanel, MainView.BUSCA_PRJ);
    }//GEN-LAST:event_buscProjActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)this.mainPanel.getLayout();
        cl.show(this.mainPanel, MainView.SIMULA_AVL);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    public void run() 
    {
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");            
            MainView mv = new MainView();
            
            ProjetoControl pc = ProjetoControl.getInstance();
            NivelControl nc = NivelControl.getInstance();
            AvaliacaoControl ac = AvaliacaoControl.getInstance();
            
            mv.mainPanel.add(pc.getBpv(),MainView.BUSCA_PRJ);
            mv.mainPanel.add(pc.getCpv(),MainView.CADASTRA_PRJ);
            mv.mainPanel.add(nc.getCnxv(),MainView.CADASTRA_XML);
            mv.mainPanel.add(ac.getEnv(),MainView.SIMULA_AVL);
            mv.setVisible(true);
            mv.setPreferredSize(new Dimension(960,720));
            mv.pack();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscProj;
    private javax.swing.JMenuItem cadProjMenuItem;
    private javax.swing.JMenuItem cadastrarXMLMenulItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem remProjMenuItem;
    // End of variables declaration//GEN-END:variables
}
