/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view.simulaAvaliacao;

import mpsbr.control.AvaliacaoControl;

/**
 *
 * @author gabriela
 */
public class EscolheNivelView extends javax.swing.JPanel {

    /**
     * Creates new form EscolheNivelView
     */
    public EscolheNivelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nivelComboBox = new javax.swing.JComboBox<>();
        nivelButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Simulação de Avaliação");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel2.setText("Selecione o nível:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        nivelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nível A", "Nível B", "Nível C", "Nível D", "Nível E", "Nível F", "Nível G", " " }));
        add(nivelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 320, -1));

        nivelButton.setText("Escolher nível");
        nivelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelButtonActionPerformed(evt);
            }
        });
        add(nivelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nivelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelButtonActionPerformed
        // TODO add your handling code here:
        AvaliacaoControl.getInstance().startAval((String) nivelComboBox.getSelectedItem());
    }//GEN-LAST:event_nivelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nivelButton;
    private javax.swing.JComboBox<String> nivelComboBox;
    // End of variables declaration//GEN-END:variables
}
