/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view.simulaAvaliacao;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import mpsbr.control.AvaliacaoControl;
import mpsbr.model.Processo;
import mpsbr.view.MainView;

/**
 *
 * @author gabriela
 */
public class ExibeResultadoView extends javax.swing.JPanel {

    /**
     * Creates new form ExibeResultadoView
     */
    public ExibeResultadoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultProcessoTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        resultadoLabel = new javax.swing.JLabel();
        nivelLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        salvaAvalButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Simulação de Avaliação");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Resultado de Avaliação");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        resultProcessoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultProcessoTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 640, 160));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Resultado Final");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        resultadoLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        resultadoLabel.setText("Satisfeito");
        add(resultadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        nivelLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nivelLabel.setText("Nível X");
        add(nivelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        salvaAvalButton.setText("Salvar Avaliação");
        salvaAvalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaAvalButtonActionPerformed(evt);
            }
        });
        add(salvaAvalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void salvaAvalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaAvalButtonActionPerformed
        AvaliacaoControl ac = AvaliacaoControl.getInstance();
        ac.saveAval();
        MainView.showPanel(MainView.NIVEL_AVL);
    }//GEN-LAST:event_salvaAvalButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainView.showPanel(MainView.NIVEL_AVL);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nivelLabel;
    private javax.swing.JTable resultProcessoTable;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JButton salvaAvalButton;
    // End of variables declaration//GEN-END:variables

    public void loadScreen() {

        AvaliacaoControl ac = AvaliacaoControl.getInstance();
        this.nivelLabel.setText("Nivel " + ac.getCurrentAval().getNivel().getNome());
        Vector<String> colunas = new Vector<>();

        colunas.add("Processo");
        colunas.add("Resultado");

        DefaultTableModel modelResults = new DefaultTableModel(colunas, 0);

        this.resultProcessoTable.setModel(modelResults);
        this.resultProcessoTable.setEnabled(true);
        this.jScrollPane1.setVisible(true);
        
        for (Processo processo : ac.getListProcessos()) {
            modelResults.addRow(new String[] {processo.getNome(), processo.getStatus()});
        }
        
        resultadoLabel.setText(ac.getCurrentAval().getStatus());
    }
}

