/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view.cadastraNivel;

import java.util.List;
import java.util.Map;

/**
 *
 * @author gabriela
 */
public class addREProcessoView extends javax.swing.JPanel {

    private Map<String, List<String>> procs;
    /**
     * Creates new form addREProcessoView
     */
    public addREProcessoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        procComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        reList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Nível");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setText("Selecione o processo: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        procComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                procComboBoxItemStateChanged(evt);
            }
        });
        add(procComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, -1));

        jScrollPane3.setViewportView(reList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 90));

        jLabel3.setText("REs Cadastrados:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton2.setText("Cancelar");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jButton4.setText("Adicionar Novo RE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jButton5.setText("Finalizar");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void procComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_procComboBoxItemStateChanged
        // TODO add your handling code here:
        int i;
        if (evt.getStateChange() == evt.SELECTED) {
          String item = (String) evt.getItem();
          
            for(String s : procs.keySet()){
                if(item.equals(s)){
                    String[] arrRe = new String[procs.get(s).size()];
                    i = 0;
                    for(String re : procs.get(s)){
                        arrRe[i] = re;
                        i++;
                    }
                    this.reList.setListData(arrRe);
                    break;
                }
            }
            this.validate();
            this.repaint();
       }
    }//GEN-LAST:event_procComboBoxItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> procComboBox;
    private javax.swing.JList<String> reList;
    // End of variables declaration//GEN-END:variables

    public void loadScreen(Map<String, List<String>> procs) {
        this.procs = procs;
        
        for(String s : procs.keySet()){
            this.procComboBox.addItem(s);
        }
        
        this.validate();
        this.repaint();
        
    }
}
