/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view.cadastraNivel;

import javax.swing.JOptionPane;
import mpsbr.view.*;
import mpsbr.control.NivelControl;
import mpsbr.model.AtributoDeProcesso;
import mpsbr.model.Processo;

/**
 *
 * @author gabriela
 */
public class ConsultaNivelView extends javax.swing.JPanel {

    /**
     * Creates new form BuscaProjetoView
     */
    public ConsultaNivelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        processoLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        buscarProcButton = new javax.swing.JButton();
        processoComboBox = new javax.swing.JComboBox<>();
        apLabel = new javax.swing.JLabel();
        apComboBox = new javax.swing.JComboBox<>();
        buscarAPButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Consulta Nível");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        processoLabel.setText("Selecione o processo:");
        add(processoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        buscarProcButton.setText("Buscar Informações");
        buscarProcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProcButtonActionPerformed(evt);
            }
        });
        add(buscarProcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 150, -1));

        processoComboBox.setMaximumRowCount(20);
        processoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                processoComboBoxItemStateChanged(evt);
            }
        });
        processoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processoComboBoxActionPerformed(evt);
            }
        });
        add(processoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, -1));

        apLabel.setText("Selecione o atributo de processo:");
        add(apLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        apComboBox.setMaximumRowCount(20);
        apComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                apComboBoxItemStateChanged(evt);
            }
        });
        apComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apComboBoxActionPerformed(evt);
            }
        });
        add(apComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 170, -1));

        buscarAPButton.setText("Buscar Informações");
        buscarAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAPButtonActionPerformed(evt);
            }
        });
        add(buscarAPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_processoComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_processoComboBoxItemStateChanged

    private void processoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processoComboBoxActionPerformed

    private void buscarProcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProcButtonActionPerformed
        String cod = (String) processoComboBox.getSelectedItem();
        if(cod != null)
        {
            Processo p = null;
            NivelControl nc = NivelControl.getInstance();
            for (Processo processo : nc.getProcessos().keySet()) {
                if(processo.getCodigo().equals(cod)){
                    p = processo;
                    break;
                }
            }
            nc.consultaProc(p, nc.getProcessos().get(p));
        }
        else
            JOptionPane.showMessageDialog(this, "Selecione um Processo para continuar");

    }//GEN-LAST:event_buscarProcButtonActionPerformed

    private void apComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_apComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_apComboBoxItemStateChanged

    private void apComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apComboBoxActionPerformed

    private void buscarAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAPButtonActionPerformed
        String cod = (String) apComboBox.getSelectedItem();
        if(cod != null)
        {
            AtributoDeProcesso ap = null;
            NivelControl nc = NivelControl.getInstance();
            for (AtributoDeProcesso atr : nc.getAp()) {
                if (atr.getCodigo().equals(cod)) {
                    ap = atr;
                    break;
                }
            }
            nc.consultaAp(ap);
        }
        else
            JOptionPane.showMessageDialog(this, "Selecione um Atributo de Processo para continuar");
    }//GEN-LAST:event_buscarAPButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        MainView.showPanel(MainView.SEL_CONS_NIVEL);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> apComboBox;
    private javax.swing.JLabel apLabel;
    private javax.swing.JButton buscarAPButton;
    private javax.swing.JButton buscarProcButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> processoComboBox;
    private javax.swing.JLabel processoLabel;
    // End of variables declaration//GEN-END:variables

    public void loadScreen() {
        NivelControl nc = NivelControl.getInstance();
        this.processoComboBox.removeAllItems();
        this.apComboBox.removeAllItems();
        for (Processo proc : nc.getProcessos().keySet()) {
            processoComboBox.addItem(proc.getCodigo());
        }
        for (AtributoDeProcesso ap : nc.getAp()) {
            apComboBox.addItem(ap.getCodigo());
        }
        this.validate();
        this.repaint();
    }
}
