/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpsbr.view.cadastraNivel;

import java.util.List;
import java.util.Map;
import mpsbr.control.NivelControl;
import mpsbr.model.AtributoDeProcesso;
import mpsbr.model.Processo;
import mpsbr.model.ResultadoEsperado;

/**
 *
 * @author gabriela
 */
public class mainCadastroNivelView extends javax.swing.JPanel {

    /**
     * Creates new form cadastraProcessosNivelView
     */
    public mainCadastroNivelView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        processoList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        changeProcButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        APList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        finalizaCadastroButton = new javax.swing.JToggleButton();
        addProcessoButton = new javax.swing.JToggleButton();
        addAPButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeNivel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Nível");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jScrollPane3.setViewportView(processoList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 90));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Processos Cadastrados:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        changeProcButton.setText("Adicionar RE em Processo Existente");
        changeProcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeProcButtonActionPerformed(evt);
            }
        });
        add(changeProcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 240, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 360, 10));

        jScrollPane5.setViewportView(APList);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("APs Cadastrados:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        finalizaCadastroButton.setText("Finalizar Cadastro");
        finalizaCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizaCadastroButtonActionPerformed(evt);
            }
        });
        add(finalizaCadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, -1));

        addProcessoButton.setText("Adicionar Novo Processo");
        addProcessoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProcessoButtonActionPerformed(evt);
            }
        });
        add(addProcessoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, -1));

        addAPButton.setText("Adicionar Novo AP");
        addAPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAPButtonActionPerformed(evt);
            }
        });
        add(addAPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Status:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nivel ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        nomeNivel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(nomeNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void changeProcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeProcButtonActionPerformed
        // TODO add your handling code here:
        NivelControl.getInstance().addREProcess();
    }//GEN-LAST:event_changeProcButtonActionPerformed

    private void addProcessoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProcessoButtonActionPerformed
        // TODO add your handling code here:
        NivelControl.getInstance().cadastroProcesso();
    }//GEN-LAST:event_addProcessoButtonActionPerformed

    private void finalizaCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizaCadastroButtonActionPerformed
        NivelControl.getInstance().finalizaCadastro();
    }//GEN-LAST:event_finalizaCadastroButtonActionPerformed

    private void addAPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAPButtonActionPerformed
        NivelControl.getInstance().cadastroAP();
    }//GEN-LAST:event_addAPButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> APList;
    private javax.swing.JToggleButton addAPButton;
    private javax.swing.JToggleButton addProcessoButton;
    private javax.swing.JToggleButton changeProcButton;
    private javax.swing.JToggleButton finalizaCadastroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomeNivel;
    private javax.swing.JList<String> processoList;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    public void loadScreen(Map<Processo, List<ResultadoEsperado>>processos, List<AtributoDeProcesso> aps){
        String[] processosCods = new String[processos.size()];
        String[] apsCods = new String[aps.size()];
        NivelControl nc = NivelControl.getInstance();
        int i = 0;
        for (Processo p : processos.keySet()) {
            processosCods[i] = p.getCodigo();
            i++;
        }
        i = 0;
        for (AtributoDeProcesso ap : aps) {
            apsCods[i] = ap.getCodigo();
            i++;
        }
        this.processoList.setListData(processosCods);
        this.APList.setListData(apsCods);
        this.nomeNivel.setText(nc.getNivel().getNome());
        this.statusLabel.setText(nc.getNivel().getStatus());
        this.validate();
        this.repaint();
    }
    
}
